export const RESET = "RESET";

export const SET_SHACKS_DATA = "SET_SHACKS_DATA";
export const SET_SHACKS_IS_LOADING = "SET_SHACKS_IS_LOADING";
export const SET_SHACKS_ERROR = "SET_SHACKS_ERROR";

export const SET_RESERVATIONS_DATA = "SET_RESERVATIONS_DATA";
export const SET_RESERVATIONS_IS_LOADING = "SET_RESERVATIONS_IS_LOADING";
export const SET_RESERVATIONS_ERROR = "SET_RESERVATIONS_ERROR";
